modLoader="javafml"
loaderVersion="[${loader_version},)"
license="GPLv3"
issueTrackerURL="https://github.com/MeinKraft/Crimson-Goats/issues"

[[mods]]
modId="crimsongoats"
updateJSONURL = "https://github.com/MeinKraft/Crimson-Goats/raw/main/update.json"
version="1.17.1-1.0.2"
displayName="Crimson Goats"
authors="ยง4Crimson_Fluff"
logoFile="logo.png"
description=''' "Head Butter Nutter" '''
